# Generated by Django 4.2.2 on 2023-06-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("full_name", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
