# Generated by Django 4.2.2 on 2023-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_usersmodel_options_alter_usersmodel_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersmodel",
            name="username",
            field=models.CharField(default="Biba", max_length=150, unique=True),
        ),
    ]
