# Generated by Django 4.2.2 on 2023-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_usersmodel_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersmodel",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
